### PR TITLE
Debian

### PR DESCRIPTION
**Pull request by cholmcc**
This PR adds the sub-directory `debian` for easy Debian (and hence Ubuntu) packaging.   To package the project, simply do 

    python3 setup.py sdist  -d ../ 
    n=`python3 setup.py --name`; v=`python setup.py --version` ; mv ../${n}-${v}.tar.gz ../${n}_${v}.orig.tar.gz
    dpkg-buildpackage -us -uc -tc -i"\.git|examples/alien.py"

Note, the package isn't really distribution quality as some things are missing, but this PR provides a starting point.   I'm not too familiar with Python packaging for RPM systems, so I do not have anything for that.

### CODE REVIEW

**Comment by adriansev** [comment]
@cholmcc it would seem that this PR contains all other commits .. could you split them so each PR contain distinct (review-able :) ) features? As it is now i cannot accept this because the setup.py must be discussed (i am not sure if when building for cvmfs it is used, if not the gnureadline dependency can be removed) and the console-scripts i cannot accept as there is a need of clear shortcuts to replace the old ones.
Thanks a lot!!

**Comment by cholmcc** [comment]
Concerning the console scripts.  

I'm not sure you've understood what is going on.  If you apply the patch (it is in a separate commit so it's easy to extract), and than do 

    python setup.py install --user 

you will end up with 

    ~/.local/bin/alien_cmd
    ~/.local/bin/alien_cp
    ~/.local/bin/alien_find
    ~/.local/bin/alien_guid2lfn
    ~/.local/bin/alien_lfn2guid
    ~/.local/bin/alien_ls
    ~/.local/bin/alien_mirror
    ~/.local/bin/alien_mkdir
    ~/.local/bin/alien_mv
    ~/.local/bin/alien_pfn
    ~/.local/bin/alien_ps
    ~/.local/bin/alien_rm
    ~/.local/bin/alien_rmdir
    ~/.local/bin/aliensh
    ~/.local/bin/alien_stat
    ~/.local/bin/alien_submit
    ~/.local/bin/alien-token-info
    ~/.local/bin/alien-token-init
    ~/.local/bin/alien_whereis

As you can see, all the scripts are there.  If you open one of them - say `alien_cp`, you see 

    #!/usr/bin/python3
    # EASY-INSTALL-ENTRY-SCRIPT: 'xjalienfs','console_scripts','alien_cp'
    __requires__ = 'xjalienfs'
    import re
    import sys
    from pkg_resources import load_entry_point
    
    if __name__ == '__main__':
        sys.argv[0] = re.sub(r'(-script\.pyw?|\.exe)?$', '', sys.argv[0])
        sys.exit(
            load_entry_point('xjalienfs', 'console_scripts', 'alien_cp')()
        )

which means that it essentially does 

    import xjalienfs.alien as a 
    a.do_cp()

and so on for all the other script (save `alien_pfn` as explained earlier).  

What this means, is that _all_ the scripts are available after installation.  What is more, the scripts are Done Right(TM) according to the Pythonic way - i.e., no hard-coded paths and so on.   This will also work with Python environments. 

As a developer, you can do 

    python setup.py develop --user 

to create an installation that points to your development tree and you have the scripts available to you.  Again, it will work with Python environments.  

The current scripts are _very_ error prone as they assume that `alien.py` is in the `PATH` - iwhich is actually not true after 

    python setup.py install 

(by default, it will go into `/usr/local/lib/python3.8/site-packages/xjsalienfs` which should certainly not be part of `PATH`).   The PR fixes this problem seamlessly _and_ makes it much easier to distribute the package.  Furthermore, it moves almost all code into Python rather than the shell.  In fact, the current approach is explicitly broken on some OS as there's no clear shell command (much less bash). 

I strongly recommend that you try an install after the patch is applied to get a better idea of what is going on. 

Yours,

Christian

**Comment by adriansev** [comment]
i understood that they are dynamically created at install step, but i do not want that, at least not personally :) ..i will discuss with the central team (that do the actual publishing in cvmfs and maintain the alidist relevant scripts) about this
also, you are absolutely correct that alien.py should be placed in bin directory or at least a symlink to xjalienfs location and my default expectation is that alien.py as well as the other shortcuts is in path. 
Thank you!

**Comment by cholmcc** [comment]
I'm not sure I understand your reluctance - using [entry-points](https://packaging.python.org/specifications/entry-points/) like this is how practically _all_ [PyPi](pypi.org) packages does it - and with good reason as outlined in the linked documentation. 

For development work you do not need the separate scripts (though you could, but that would be duplicating code) as you can use 

    python setup.py develop 

This only needs to be done _once_.  

Finally, for `alidist` and deployment on CVMFS it would be much easier to maintain - no need to configure PATH beyond adding the regular `bin` directory (which is probably already there) or fix-up directories with sym-links or the like.  The build part of the `alidist` script would go from 

    env PYTHONUSERBASE="$INSTALLROOT" ALIBUILD=1 pip3 install --user file://${SOURCEDIR}
    XJALIENFS_SITEPACKAGES=$(find ${INSTALLROOT} -name site-packages)
    
    ALIEN_PY=$(find ${INSTALLROOT} -name alien.py)
    
    cp -r $SOURCEDIR/bin ${INSTALLROOT}/bin
    cp ${ALIEN_PY} ${INSTALLROOT}/bin/alien.py
    chmod +x ${INSTALLROOT}/bin/*

to literally

    env PYTHONUSERBASE="$INSTALLROOT" ALIBUILD=1 pip3 install --user file://${SOURCEDIR}
    XJALIENFS_SITEPACKAGES=$(env PYTHONUSERBASE="$INSTALLROOT" python3 -m site --user-site)
    
That's a factor 3 _down_ in complexity.  Note, I use **Python** to give me the correct installation prefix. 

Finally, it will also make life a lot easier for people who do not work most of the time on CVMFS (as is the case for a lot of our colleagues ), since they can simply do 

    pip install xjalienfs 

and be done with it (well, assuming XRootD get their act together and distribute via PyPi as well :-)) 

There is nothing to loose from the _entry point_ approach and you will gain a lot on top.

**Pull request closed without merging**
